### ISSUE TITLE
metadata params

### ISSUE THREAD

**Issue by fgrimme** [sampsyo/pyacoustid#26]
is it possible to get the label of a release by setting a specific meta parameter in the lookup request?
(i'd like to suggest that you should mention somewhere that values for the meta-parameter should be seperated by whitespaces in the lookup call :)
thank you

**Comment by sampsyo** [comment]
The possible values are listed in the [Acoustid web service documentation](https://acoustid.org/webservice). (To answer your question, you may be able to get label information by using `recordings`, or you may have to do a second lookup in MusicBrainz to get that.) We should probably mention that this is the right place for details in our docs…

**Comment by fgrimme** [comment]
thank you for the answer.
the values are listed but it's not mentioned what exactly is included in the response. that's the reason why i'm asking here. i will try the second lookup in musicbrainz if the label is not included in the recordings.
